#!/bin/bash
#########################################################
###         Unalies default oh-my-zsh alieses         ###
#########################################################
# unalias ll
# unalias ls
# unalias lsa


#########################################################
###                     Aliases                       ###
#########################################################

# Usual
alias sudo="sudo "
alias cls="clear"
alias ..="cd .."
alias cd..="cd .."
alias myip="curl http://ipecho.net/plain; echo"

alias -s {mp3,m4a,flac}="mpv"
alias -s {png,jpg,tiff,bmp}="imv"
alias -s {conf,txt}="nvim"


#########################################################
####                Colored Output                    ###
#########################################################

alias grep='grep --color=auto'

alias ll="ls -l --color"
alias lsa="ls -la --color"
alias ls="ls --color"

alias snaplist="snapper -c root list"

# Clean ass
sorthist () {
	cat -n "$HISTFILE" | sort -t ';' -uk2 | sort -nk1 | cut -f2- > "$HISTFILE"short
	mv "$HISTFILE"short "$HISTFILE"
}

# cd and ls after
cd() {
	builtin cd "$@" && command ls --group-directories-first --color=auto -F
}


# распаковать архив не указывая тип распаковщика
function ex {
	if [ -z "$1" ]; then
		# display usage if no parameters given
		echo "Использование: ex <path/file_name>.<zip|rar|bz2|gz|tar|tbz2|tgz|Z|7z|xz|ex|tar.bz2|tar.gz|tar.xz>"
	else
		if [ -f "$1" ] ; then
			NAME=${1%.*}
			#mkdir $NAME && cd $NAME
			case "$1" in
				*.tar.bz2)   tar xvjf ./"$1"    ;;
				*.tar.gz)    tar xvzf ./"$1"    ;;
				*.tar.xz)    tar xvJf ./"$1"    ;;
				*.lzma)      unlzma ./"$1"      ;;
				*.bz2)       bunzip2 ./"$1"     ;;
				*.rar)       unrar x -ad ./"$1" ;;
				*.gz)        gunzip ./"$1"      ;;
				*.tar)       tar xvf ./"$1"     ;;
				*.tbz2)      tar xvjf ./"$1"    ;;
				*.tgz)       tar xvzf ./"$1"    ;;
				*.zip)       unzip ./"$1"       ;;
				*.Z)         uncompress ./"$1"  ;;
				*.7z)        7z x ./"$1"        ;;
				*.xz)        unxz ./"$1"        ;;
				*.exe)       cabextract ./"$1"  ;;
				*)           echo "ex: '$1' - Не может быть распакован" ;;
			esac
		else
			echo "'$1' - не является допустимым файлом"
		fi
	fi
}

# Упаковка в архив командой pk 7z /что/мы/пакуем имя_файла.7z
function pk () {
	if [ $1 ] ; then
		case $1 in
			tbz)       tar cjvf $2.tar.bz2 $2      ;;
			tgz)       tar czvf $2.tar.gz  $2       ;;
			txz)       tar -caf $2.tar.xz  $2       ;;
			tar)       tar cpvf $2.tar  $2       ;;
			bz2)       bzip $2 ;;
			gz)        gzip -c -9 -n $2 > $2.gz ;;
			zip)       zip -r $2.zip $2   ;;
			7z)        7z a $2.7z $2    ;;
			*)         echo "'$1' не может быть упакован с помощью pk()" ;;
		esac
	else
		echo "'$1' не является допустимым файлом"
	fi
}

paruI(){
	paru -Slq | fzf -m  --reverse --preview 'paru -Si {1}' | xargs -ro paru -S
}

paruR(){
	paru -Qqe | fzf -m --reverse --preview 'paru -Si {1}' | xargs -ro paru -Rsnc
}



