[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-oomux-dark-led
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomux-dark-led
GtkTheme=oomux-dark-led
IconTheme=oomux-dark-led
MetacityTheme=oomux-dark-led
