#!/bin/bash
# simple script to make scratchpad handling
# in sway

[ -z "$1" ] && exit

# check if window available:
if [[ -z $(swaymsg -t get_tree | grep "dropdown_$1") ]];
then

	if [ "$1" == "$TERMINAL" ]
	then
		swaymsg "exec $TERMINAL -T dropdown_$1"
		sleep 0.2
		swaymsg -q "[title=dropdown_$1] mark dropdown_$1"
	else
		swaymsg "exec $TERMINAL -T dropdown_$1 $1"
		sleep 0.2
		swaymsg "[title=dropdown_$1] scratchpad show"
	fi
fi


# get monitor geometry (return display_W and display_H)
eval "$(swaymsg -t get_outputs |\
	jq -r '.[] | select(.focused==true)|"display_W=\(.rect.width)\ndisplay_H=\(.rect.height)"')"

# get paddings from config
CONFIG=$HOME/.config/sway/config.d/theme
GAPS_INN=$(awk '/gaps inner/ {print $3}' "$CONFIG")
GAPS_OUT=$(awk '/gaps outer/ {print $3}' "$CONFIG")

# 38 is constat, depending on waybar width
TERM_W=$((  display_W - GAPS_INN * 2 + GAPS_OUT * 2 - 38 ))
TERM_H=$((  display_H * 33 / 100 ))

TERM_X=0
TERM_Y=0

swaymsg "[title=dropdown_$1]" resize  set $TERM_W $TERM_H
swaymsg "[title=dropdown_$1]" move position $TERM_X $TERM_Y

swaymsg -q "[con_mark=dropdown_$1] scratchpad show"


