#!/bin/bash
# simple script to make scratchpad handling
# in sway

[ -z "$1" ] && exit

# check if window available:
if [[ -n $(swaymsg -t get_tree | grep "dropdown_$1") ]];
then
	# echo "Window detected... showing..."
	swaymsg "[title=dropdown_$1] scratchpad show"
else
	# echo "Window not detected... spawning."

	if [ "$1" == "$TERMINAL" ]
	then

		swaymsg "exec $TERMINAL -t dropdown_$1"
		sleep 0.2
		swaymsg "[title=dropdown_$1] scratchpad show"

	elif [[ "$1" == "nvim" ]]
	then

		swaymsg "exec $TERMINAL -t dropdown_$1  -e bash -c 'sleep 0.1 && nvim "$2"' "
		sleep 0.2
		swaymsg "[title=dropdown_$1] scratchpad show"

	else

		swaymsg "exec $TERMINAL -t dropdown_$1 -e $1"
		sleep 0.2
		swaymsg "[title=dropdown_$1] scratchpad show"

	fi

fi
