emulate sh -c 'source /etc/profile'

export MOZ_ENABLE_WAYLAND=1
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
export WLR_NO_HARDWARE_CURSORS=1
export QT_QPA_PLATFORMTHEME=qt5ct

# to work with grimshot
export XDG_SCREENSHOTS_DIR=$HOME/Pictures/Screen

# Adds `~/.local/bin` to $PATH
#export PATH="$PATH:$(du "$HOME/.local/bin/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"

export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

# Default programs:
export EDITOR="nvim"
export SYSTEMD_EDITOR="nvim"
export VISUAL="nvim"
export SUDO_EDITOR="nvim"
export TERMINAL="foot"
export BROWSER="librewolf"
export READER="zathura"
export FILE="pcmanfm-qt"

# termite SSH fix
export TERM=xterm-color

# wine
# Run 'systemctl restart systemd-binfmt' in order to make the wine binfmt available on your system.
export WINEPREFIX='/home/led/Games/div'
# ESYNC
export WINEESYNC=1

# javafix for tiling wm
export _JAVA_AWT_WM_NONREPARENTING=1
# fix for java to use GTK theme
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel ${_JAVA_OPTIONS}"


# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export ZDOTDIR="$HOME/.config/zsh"

# Other program settings:
export SUDO_ASKPASS="$HOME/.local/bin/bemenupass"

export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"

# color output for man
export LESS=-R
# Start blinking
export LESS_TERMCAP_mb=$(tput bold; tput setaf 2) # green
# Start bold
export LESS_TERMCAP_md=$(tput bold; tput setaf 2) # green
# Start standout
export LESS_TERMCAP_so=$(tput bold; tput setaf 0; tput setab 2) # yellow
# End standout
export LESS_TERMCAP_se=$(tput rmso; tput sgr0)
# Start underline
export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 1) # red
# End Underline
export LESS_TERMCAP_ue=$(tput sgr0)
# End bold, blinking, standout, underline
export LESS_TERMCAP_me=$(tput sgr0)

# bemenu colors
highlight=#97D59B
background=#1F252A
BEMENU_OPTS="--fn \"IosevkaMono 14\" -H 38 -p   -l 10 -w -m all --tb $background --tf $highlight --fb $background --nb $background --hb $highlight  --hf $background  --sb #80D1FF --sf $background --scb #ff0000"

export BEMENU_OPTS


# fix for ls
export LS_COLORS="ow=30;42"

#PATH="/usr/sbin:/sbin:/bin:/usr/games:$PATH"

[[ `tty` == "/dev/tty1" ]] && exec sway

