#!/bin/sh

bat=/sys/class/power_supply/BAT1/
per="$(cat "$bat/capacity")"
stat="$(cat "$bat/status")"
max=96

#function to send notification when battery is in critical condition
notifier(){
dunstify  --urgency=CRITICAL "Battery Low" "Level: ${battery_level}%" -i battery-low \
	> /dev/null 2>&1
pw-play ~/.local/share/themes/bell.ogg \
	> /dev/null 2>&1
}

if [[ "$per" -gt "$max" && $stat != Discharging  ]]; then
	text=""
	alt=""
	class="full"
elif [ stat == Charging ]; then
	text=""
	class="charging"
elif [ "$per" -gt "90" ]; then
	text=""
	class="dis_normal"
elif [ "$per" -gt "80" ]; then
	text=""
	class="dis_normal"
elif [ "$per" -gt "70" ]; then
	text=""
	class="dis_normal"
elif [ "$per" -gt "60" ]; then
	text=""
	class="dis_normal"
elif [ "$per" -gt "50" ]; then
	text=""
	class="dis_normal"
elif [ "$per" -gt "40" ]; then
	text=""
	class="dis_normal"
elif [ "$per" -gt "30" ]; then
	text=""
	class="dis_normal"
elif [ "$per" -gt "20" ]; then
	text=""
	class="dis_warning"
elif [ "$per" -gt "10" ]; then
	text=""
	class="dis_warning"
elif [ "$per" -gt "0" ]; then
	text=""
	class="dis_crit"
	notifier
else
	text=""
	class="dis_crit"
fi

alt=$per%

echo {\"text\": \"$text\", \"alt\": \"$alt\", \"class\":\"${class}\"}
