#!/bin/bash

battery_level=$(cat /sys/class/power_supply/BAT1/capacity)
battery_status=$(cat /sys/class/power_supply/BAT1/status)

#function to send notification when battery is in critical condition
notifier(){
dunstify  --urgency=CRITICAL "Battery Low" "Level: ${battery_level}%" -i battery-low \
	> /dev/null 2>&1
pw-play ~/.local/share/themes/bell.ogg \
	> /dev/null 2>&1
}


if [[ $battery_level -gt 95 && $battery_status != Discharging ]]
then
	class=full
elif [[ $battery_status == Charging ]]
then
	class=charging
elif [[ $battery_status == Discharging && $battery_level -le 10 ]]
then
	class=dis_crit
	notifier
elif [[ $battery_status == Discharging && $battery_level -le 30 ]]
then
	class=dis_warning
elif [[ $battery_status == Discharging ]]
then
	class=dis_normal
fi

text=""
alt=""

echo {\"text\": \"$text\", \"alt\": \"$alt\", \"class\":\"${class}\"}
